### ISSUE TITLE
Error con docker-compose run web rails db:..

### ISSUE THREAD

**Issue by valeeeriquelme** [IIC2143-2019-2/proyecto#63]
Me lanza el error al tratar de ejecutar docker-compose run web rails db:create. El error es FATAL: data directory "/var/lib/postgersql/data" has wrong ownership.
Busqué en google y me recomiendan como solución trabajar con volumenes pero no entiendo mucho.

**Comment by valeeeriquelme** [comment]
Estoy trabajando con DockerToolbox

**Comment by jerosalazar** [comment]
Hola, puedes mostrarme como está tu config/database?

**Comment by daleal** [comment]
Hola! Intenta cambiando la línea de tu `docker-compose.yml` que dice `- /var/lib/postgresql/data` para que quede diciendo `- ./tmp/db:/var/lib/postgresql/data` e intenta nuevamente crear la base de datos. Si no te funciona, por favor envía (aparte de tu `config/database.yml`) tu `Dockerfile` y tu `docker-compose.yml`

**Comment by valeeeriquelme** [comment]
Hola  
**Este es mi config/database.yml**
```
default: &default
    adapter: postgresql
    encoding: unicode
    host: db
    username: postgres
    password:
    pool: 5

development:
    <<: *default
    database: myapp_development


test:
    <<: *default
    database: myapp_test
```
**Mi Dockerfile**
```
FROM ruby:2.5
RUN apt-get update -qq && apt-get install -y nodejs postgresql-client
RUN mkdir /myapp
WORKDIR /myapp
COPY Gemfile /myapp/Gemfile
COPY Gemfile.lock /myapp/Gemfile.lock
RUN bundle install
COPY . /myapp

COPY entrypoint.sh /usr/bin/
RUN chmod +x /usr/bin/entrypoint.sh
ENTRYPOINT ["entrypoint.sh"]
EXPOSE 3000

CMD ["rails", "server", "-b", "0.0.0.0"]
```
**Mi docker-compose.yml**
```
version: '3'
services:
    db:
      image: postgres
      volumes:
        - ./tmp/db:/var/lib/postgresql/data
    web:
      build: .
      command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
      volumes:
        - .:/myapp
      ports:
        - "3000:3000"
      depends_on:
        - db
```

**Comment by daleal** [comment]
Hola! Estuve leyendo y aparentemente es un error bastante documentado en Windows, pero no parece estar solucionado. Intenta lo siguiente: cambia tu `docker-compose.yml` para que quede así:

```yaml
version: '3'
services:
  db:
    image: postgres
      volumes:
        - postgresdata:/var/lib/postgresql/data
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
volumes:
  postgresdata:
```

Avísame si te funciona o no!

**Comment by valeeeriquelme** [comment]
No funcionó, me da esto:
![image](https://user-images.githubusercontent.com/37518300/64886465-a0764c80-d63c-11e9-89b6-a007820bfb4c.png)

**Comment by daleal** [comment]
Perdón, me equivoqué yo! Se me fue una indentación. El `docker-compose.yml` debería verse así:

```yaml
version: '3'
services:
  db:
    image: postgres
    volumes:
      - postgresdata:/var/lib/postgresql/data
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
volumes:
  postgresdata:
```

**Comment by valeeeriquelme** [comment]
Nu funcionó :sob: , creo que optaré por intentar con una partición

**Comment by daleal** [comment]
Qué error sale? (en todo caso yo creo que lo mejor es una partición igual)

**Comment by valeeeriquelme** [comment]
El mismo que antes  FATAL: data directory "/var/lib/postgersql/data" has wrong ownership.

**Comment by daleal** [comment]
Intenta con esto. Ejecuta el comando `docker volume create --name=postgresdata`, cambia tu `docker-compose.yml` para que se vea así:

```yaml
version: '3'
services:
  db:
    image: postgres
    volumes:
      - postgresdata:/var/lib/postgresql/data
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
volumes:
  postgresdata:
    external: true
```

Y luego ejecuta tu comando.
